{% set name = "gandlf" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CBICA/GaNDLF/archive/{{ version }}.tar.gz
  sha256: 2840fae73f245f3836d5da74c47d5e17ffd83c086b5235b6fcd74c7946a23165

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - torchio ==0.18.57
    - pytorch >=1.7
    - numpy ==1.22.0
    - scipy
    - tqdm
    - pandas
    - pylint
    - scikit-learn >=0.23.2
    - pickle5 >=0.0.11
    - setuptools
    - seaborn
    - pyyaml
    - scikit-image
    - matplotlib-base
    - requests
    - libvips
    - pyvips
    - pytest
    - python >=3.8
    - torchvision
    - deprecated >=1.2.5
    - medcam
    - opencv
    - psutil
    - coverage
    - SimpleITK !=2.0.*
    - pytest-azurepipelines
    - pkgconfig
    - torchmetrics ==0.5.1
    - tiffslide
    - pydicom
    - OpenPatchMiner ==0.1.8
    - onnx

test:
  imports:
    - GANDLF
    - GANDLF.utils
    - GANDLF.models
    - GANDLF.compute

about:
  home: https://github.com/CBICA/GaNDLF
  license: LicenseRef-CBICA
  license_family: BSD
  license_file: LICENSE
  summary: The Generally Nuanced Deep Learning Framework for segmentation, regression and classification.
  doc_url: https://cbica.github.io/GaNDLF/
  dev_url: https://cbica.github.io/GaNDLF/extending

extra:
  recipe-maintainers:
    - AlexanderGetka-cbica
    - sarthakpati
