{% set name = "gandlf" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CBICA/GaNDLF/archive/{{ version }}.tar.gz
  sha256: 173140e29a5f4dc7817e43312562eb4b9adc51cb7254e45990e6a9d92f6d0a5f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - openslide
  run:
    - torchio ==0.18.29
    - pytorch >=1.7
    - numpy ==1.19.2
    - scipy
    - tqdm
    - pandas
    - pylint
    - scikit-learn ==0.23.1
    - pickle5 ==0.0.11
    - setuptools
    - seaborn
    - pyyaml
    - libvips
    - openslide
    - scikit-image
    - matplotlib-base
    - requests
    - pyvips
    - pytest
    - python >=3.6
    - torchvision
    - deprecated >=1.2.5
    - medcam
    - opencv
    - psutil
    - openslide-python >=1.1.2
    - coverage
    - SimpleITK ==1.2.4
    - pytest-azurepipelines
    - pkgconfig
    - torchmetrics

test:
  imports:
    - GANDLF
    - GANDLF.models
    - GANDLF.utils

about:
  home: https://github.com/CBICA/GaNDLF
  license: LicenseRef-CBICA
  license_family: BSD
  license_file: LICENSE
  summary: The Generally Nuanced Deep Learning Framework for segmentation, regression and classification.
  doc_url: https://cbica.github.io/GaNDLF/
  dev_url: https://cbica.github.io/GaNDLF/extending

extra:
  recipe-maintainers:
    - sarthakpati
